customhost = "database-1.cql6qopjwdm7.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leowcheeyew-employee"
customregion = "us-east-1"
